services:
  - type: web
    name: discover-afrika-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: PORT
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: FLW_PUBLIC_KEY
        sync: false
      - key: FLW_SECRET_KEY
        sync: false
      - key: FLW_ENCRYPTION_KEY
        sync: false
      - key: FLW_BASE_URL
        sync: false
      - key: FLW_SECRET_HASH
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: CLOUD_NAME
        sync: false
      - key: CLOUD_API_KEY
        sync: false
      - key: CLOUD_API_SECRET
        sync: false
      # Add any other environment variables your app needs